server:
  port: 9090
  tomcat:
    max-connections: 1000
    threads:
      max: 1000
      min-spare: 100
    max-http-form-post-size: 10MB
    max-swallow-size: 10MB
spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  application:
    name: sharding-demo
  shardingsphere:
    #\u6570\u636E\u5E93\u8FDE\u63A5\u4FE1\u606F
    datasource:
      names: db0,db1
      db0:
        #连接池类型
        type: com.zaxxer.hikari.HikariDataSource
        #mysql url
        jdbc-url: jdbc:mysql://localhost:3306/ds0?zeroDateTimeBehavior=CONVERT_TO_NULL&useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8&autoReconnct=true&autoReconnectForPools=true
        #连接驱动
        driver-class-name: com.mysql.cj.jdbc.Driver
        #用户名
        username: root
        #密码
        password: root
        #最大连接数，默认是10
        maximum-pool-size: 50
        #连接归还后是否自动提交未提交的事务，默认true
        auto-commit: false
        #连接最大生命周期，0代表无限生命周期
        max-lifetime: 600000
        #连接池名称
        pool-name: ${spring.application.name}-pool0
        #最小空闲连接数
        minimum-idle: 10
        #数据库连接超时时间，默认30秒
        connection-timeout: 30000
        #空闲连接最大存活时间
        idle-timeout: 60000
        #连接校验超时时间
        validation-timeout: 3000
        #连接检测sql
        connection-test-query: select 1
      db1:
        #连接池类型
        type: com.zaxxer.hikari.HikariDataSource
        #mysql url
        jdbc-url: jdbc:mysql://localhost:3306/ds1?zeroDateTimeBehavior=CONVERT_TO_NULL&useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8&autoReconnct=true&autoReconnectForPools=true
        #连接驱动
        driver-class-name: com.mysql.cj.jdbc.Driver
        #用户名
        username: root
        #密码
        password: root
        ##连接池名称
        pool-name: ${spring.application.name}-pool1
        #最大连接数，默认是10
        maximum-pool-size: 50
        #连接最大生命周期，0代表无限生命周期
        max-lifetime: 600000
        #连接归还后是否自动提交未提交的事务，默认true
        auto-commit: false
        #最小空闲连接数
        minimum-idle: 10
        #数据库连接超时时间，默认30秒
        connection-timeout: 30000
        #空闲连接最大存活时间
        idle-timeout: 60000
        #连接校验超时时间
        validation-timeout: 3000
        #连接检测sql
        connection-test-query: select 1
    sharding:
      #分库配置
      default-database-strategy:
        inline:
          sharding-column: student_id
          algorithm-expression: db$->{student_id%2}
      #分表配置
      tables:
        student:
          actual-data-nodes: db$->{0..1}.student$->{0..1}
          table-strategy:
            inline:
              sharding-column: student_id
              algorithm-expression: student$->{student_id%2}
    #org.apache.shardingsphere.underlying.common.config.properties.ConfigurationPropertyKey
    props:
      sql:
        show: false
#==============================================================
#mybatis-plus配置
#==============================================================
mybatis-plus:
  mapper-locations: classpath*:/mappers/*.xml
  type-aliases-package: com.sharding.demo.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: assign_id
      select-strategy: not_empty
      update-strategy: not_null
      insert-strategy: not_null